# Generated by Django 4.2.5 on 2023-09-08 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='FirstFormModel',
        ),
    ]
