# Generated by Django 4.2.5 on 2023-09-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstform', '0002_rename_member_firstformmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('hobby', models.CharField(max_length=255)),
            ],
        ),
    ]
